name: Test make new release

on:
  push:
    branches: ["julia-release"]

jobs:
  check-version:
    name: Check version number for changes
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.version_tag.outputs.tag }}
      release: ${{ steps.release.outputs.release }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Pull
      run: git clone https://github.com/quadraturerules/quadraturerules.git .
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    - name: Get latest tag
      id: release_tag
      run: echo -n "tag=$(git describe --tags `git rev-list --tags --max-count=1`)" >> $GITHUB_OUTPUT
    - name: Get version
      id: version_tag
      run: echo -n "tag=v$(cat VERSION)" >> $GITHUB_OUTPUT

    - name: Compare version numbers
      run: |
        if [ "${{ steps.release_tag.outputs.tag }}" = "${{ steps.version_tag.outputs.tag }}" ]; then
           echo "release=no" >> $GITHUB_OUTPUT
        else
           echo "release=yes" >> $GITHUB_OUTPUT
        fi
      id: release


  julia-library:
    name: Release Julia library
    runs-on: ubuntu-22.04
    permissions:
      id-token: write
    needs:
      - check-version
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: Install PyGitHub
        run: python3 -m pip install PyGitHub
      - name: Make release
        run: python3 .github/scripts/julia_release.py ${{ secrets.JULIA_REPO_TOKEN }} ${{ needs.check-version.outputs.tag }}
